openapi: 3.0.2
info:
  title: 'OpenAPI spec for an environmental data gathering IoT field device API resources'
  version: 1.0.0
  description: |-
    OpenAPI spec for an environment data gathering IoT field device API resources:
      - GET temperature, humidity, pressure, ambient light intensity readings
      - GET Health checks
servers:
  - url: 'http://192.168.1.77:8080/iotenv/api/v1'
    description: The field device endpoint
paths:
  /sensors/bh1750:
    summary: The ambient light intensity BH1750 sensor readings
    description: |-
      This resource allows to obtain light intensity readings
      from the BH1750 ambient light intensity sensor
    get:
      tags: [ ]
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sensor_readings_item_type'
              examples:
                bh1750_ambient_light_intensity_readings_example_1:
                  value:
                    s_type: LIGHT
                    s_name: 'BH1750'
                    s_data: '1.67'
                    s_timestamp: '2021-08-22T22:44:20.369467Z'
          description: The BH1750 ambient light intensity sensor readings
        '500':
          $ref: '#/components/responses/sensor_error'
      operationId: GetBH1750AmbientLightIntensity
      summary: Get BH1750 ambient light intensity readings
      description: Can be used to get readings from BH1750 ambient light intensity sensor
  /sensors/bmp180:
    summary: The BMP180 pressure sensor readings
    description: |-
      This resource allows to obtain pressure readings from the BMP180 pressure sensor
      Temperature measurement included
    get:
      tags: [ ]
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sensor_readings_item_type'
              examples:
                bmp180_temperature_pressure_readings_example_1:
                  value:
                    s_readings:
                      - s_id: '55'
                        s_type: TEMP
                        s_name: 'BMP180'
                        s_data: '25.089'
                        s_timestamp: '2021-09-20T19:34:10.119467Z'
                      - s_id: '55'
                        s_type: PRESS
                        s_name: 'BMP180'
                        s_data: '69964'
                        s_timestamp: '2021-09-20T19:34:10.119467Z'
          description: |
            The collection of temperature and pressure readings, obtained from
            the BMP180 environmental data sensor
        '500':
          $ref: '#/components/responses/sensor_error'
      operationId: GetBMP180TempPress
      summary: Get BMP180 temperature and pressure readings
      description: Can be used to get readings from BMP180 pressure sensor
  /sensors/sht3x:
    summary: The SHT3x humidity and temperature sensor readings
    description: |-
      This resource allows to obtain humidity and temperature readings from the SHT3x environmental sensor
    get:
      tags: [ ]
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sensor_readings_item_type'
              examples:
                sht3x_humidity_temperature_readings_example_1:
                  value:
                    s_readings:
                      - s_type: HUMID
                        s_name: 'SHT3x'
                        s_data: '75.7'
                        s_timestamp: '2021-10-08T14:24:10.119467Z'
                      - s_type: TEMP
                        s_name: 'SHT3x'
                        s_data: '15.39'
                        s_timestamp: '2021-10-08T14:24:10.119467Z'
          description: |
            The collection of humidity and temperature readings, obtained from 
            the SHT3x environmental data sensor
        '500':
          $ref: '#/components/responses/sensor_error'
      operationId: GetSHT3xHumidTemp
      summary: Get SHT3x humidity and temperature readings
      description: Can be used to get readings from SHT3x humidity and temperature sensor
  /sensors/bme280:
    summary: 'The temperature, humidity and pressure BME280 sensor readings'
    description: |-
      This resource allows to obtain temperature, humidity, and pressure readings
      from the BME280 environmental data sensor
    get:
      tags: [ ]
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sensor_readings_type'
              examples:
                bme280_thp_readings_example:
                  value:
                    s_readings:
                      - s_id: '60'
                        s_type: TEMP
                        s_data: '26.079965189471842'
                        s_timestamp: '2021-08-22T18:10:55.736630Z'
                      - s_id: '60'
                        s_type: HUMID
                        s_data: '45.481067387147625'
                        s_timestamp: '2021-08-22T18:10:55.736630Z'
                      - s_id: '60'
                        s_type: PRESS
                        s_data: '99556.74677629767'
                        s_timestamp: '2021-08-22T18:10:55.736630Z'
          description: |-
            The collection of temperature, humidity, and pressure readings, obtained from
            the BME280 environmental data sensor
        '500':
          $ref: '#/components/responses/sensor_error'
      operationId: GetBME280THP
      summary: 'Get temperature, humidity and pressure readings from BME280'
      description: |-
        Can be used to get readings of temperature, humidity, and pressure readings,
        obtained from the BME280 environmental data sensor
  /sensors/system:
    summary: 'The health current state and health data, e.g. CPU temperature, free memory, etc.'
    description: |-
      This resource allows to obtain system current state and health data,
      e.g. CPU temperature, free memory, obtained from the SBC OS
    get:
      tags: [ ]
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sensor_readings_type'
              examples:
                system_readings_example:
                  value:
                    s_readings:
                      - s_type: CPU_TEMP
                        s_data: '56.012'
                        s_timestamp: '2021-08-22T18:10:55.736630Z'
                      - s_type: DISK_SPACE_FREE
                        s_data: '5046586572'
                        s_timestamp: '2021-08-22T18:10:55.736630Z'
                      - s_type: DISK_SPACE_TOTAL
                        s_data: '5046586572'
                        s_timestamp: '2021-08-22T18:10:55.736630Z'
                      - s_type: HEAP_MEMORY_USED
                        s_data: '26109542.4'
                        s_timestamp: '2021-08-22T18:10:55.736630Z'
                      - s_type: HEAP_MEMORY_TOTAL
                        s_data: '50331648'
                        s_timestamp: '2021-08-22T18:10:55.736630Z'
                      - s_type: HEAP_MEMORY_MAX
                        s_data: '68052582.8'
                        s_timestamp: '2021-08-22T18:10:55.736630Z'
          description: |-
            The collection of system state and health data readings, obtained from the SBC OS
        '500':
          $ref: '#/components/responses/sensor_error'
      operationId: GetSystemData
      summary: 'Get health state and health data from the SBC OS'
      description: |-
        Can be used to get readings of system state and health data readings, obtained from the SBC OS
components:
  schemas:
    sensor_readings_type:
      description: An array of sensors readings
      type: object
      properties:
        s_readings:
          description: Sensor readings
          type: array
          items:
            $ref: '#/components/schemas/sensor_readings_item_type'
      example:
        s_readings:
          - s_id: '60'
            s_name: 'BME280'
            s_type: TEMP
            s_data: '26.079965189471842'
            s_timestamp: '2021-08-22T18:10:55.736630Z'
          - s_id: '60'
            s_name: 'BME280'
            s_type: HUMID
            s_data: '45.481067387147625'
            s_timestamp: '2021-08-22T18:10:55.736630Z'
          - s_id: '60'
            s_name: 'BME280'
            s_type: PRESS
            s_data: '99556.74677629767'
            s_timestamp: '2021-08-22T18:10:55.736630Z'
    sensor_readings_item_type:
      description: |
        A structure, containing the BME280 sensor data readings,
        e.g. temperature, humidity, pressure, etc.
      required:
        - s_data
        - s_timestamp
      type: object
      properties:
        s_type:
          description: |
            A sensor type, e.g. TEMP (temperature)
          type: string
        s_id:
          description: Sensor id
          type: string
        s_name:
          description: Sensor name
          type: string
        s_data:
          description: A sensor readings value
          type: string
        s_timestamp:
          format: date-time
          description: Readings fetch timestamp
          type: string
      example:
        s_id: '55'
        s_name: 'BMP180'
        s_type: TEMP
        s_data: '26.079965189471842'
        s_timestamp: '2021-08-22T18:10:55.736630Z'
    sensor_error_type:
      description: |
        This type contains a sensor readings request error description elements of the API
      required:
        - event_id
        - event_name
        - event_timestamp
      type: object
      properties:
        event_id:
          description: An error event type id
          type: string
        event_name:
          description: An error event descriptive name
          type: string
        s_name:
          description: A sensor type, e.g. BH1750 (Ambient light)
          type: string
        s_type:
          description: A sensor name, e.g. TEMP (temperature)
          type: string
        desc:
          description: An error event detailed info
          type: string
        event_timestamp:
          format: date-time
          description: An error event occurrence timestamp
          type: string
      example:
        event_id: E-BH1750-0001
        event_name: BH1750 data read error
        s_type: LIGHT
        s_name: BH1750
        desc: |
          dev.sergevas.iot.env.shared.exception.SensorException:
          BH1750 data read error
          Caused by: java.lang.RuntimeException: Test exception
        event_timestamp: '2021-08-22T20:34:51.809518Z'
  responses:
    sensor_error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/sensor_error_type'
          examples:
            sensor_error_example_1:
              value:
                event_id: E-BH1750-0001
                event_name: BH1750 data read error
                s_type: LIGHT
                desc: |
                  dev.sergevas.iot.env.shared.exception.SensorException:
                  BH1750 data read error
                  Caused by: java.lang.RuntimeException: Test exception
                event_timestamp: '2021-08-22T20:34:51.809518Z'
      description: A sensor error message
